### ISSUE TITLE
Better instructions in README?

### ISSUE THREAD

**Issue by geerlingguy** [runborg/vyos-pi-builder#1]
I'm thinking of giving this a spin on a couple Pi CM4s, but I think there are some baked in assumptions in the README that someone new to VyOS might not know.

For example, there's a step:

```
build the vyos-build docker container as vyos/vyos-build:current-arm64
```

But I'm not quite sure where the `Dockerfile` for that is (is it in this repo, or elsewhere?), nor if there are any other things I'd need to do to actually run the build (e.g. configure things for ARM64 vs AMD64).

(I found this repo through https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/114)

**Comment by runborg** [comment]
Hi Jeff! I've updated the readme with build instructions for the docker container, please give me a hint if this is enough.

**Comment by geerlingguy** [comment]
@runborg - Ah, much better! I'll try to give it a spin.
