### ISSUE TITLE
make iso-* failed: unknown flag: --arch

### ISSUE THREAD

**Issue by jkuettner** [runborg/vyos-pi-builder#12]
Hi,

apparently building an image using the Makefile does not seem to work:

```shell
$ make iso-local
sudo docker run --rm -it --arch arm64 --privileged -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -v "/tmp/vyos-pi-builder":/vyos -v /dev:/dev --sysctl net.ipv6.conf.lo.disable_ipv6=0 localhost/vyos/vyos-build:current-arm64 /bin/bash -c 'cd /vyos; /bin/bash -x build-image.sh'
unknown flag: --arch
See 'docker run --help'.
make: *** [Makefile:8: iso-local] Fehler 125
```

To my knowledge, docker has never had the flags `--args`. I wonder what I am missing here

**Comment by runborg** [comment]
@kaplan-michael i think this comes from your PR

**Comment by kaplan-michael** [comment]
@runborg @jkuettner yeah seems an oversight at my side(tested with podman) It should probably be `--platform linux/arm64`
I'll spin up some machine with docker and test it.
