### ISSUE TITLE
make container failed: unknown shorthand flag: 'v' in -v

### ISSUE THREAD

**Issue by jkuettner** [runborg/vyos-pi-builder#13]
Hi,

in addition to my [previous issue](#12 ), I also noticed that `make container` fails with the same error.
However, if you omit `--arch`, the command may not work either, as it tries to mount `qemu-aarch64-static` during the build process, and docker has no support for mounting files when building a container image:

```shell
$ sudo docker build vyos-build/docker -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -t vyos/vyos-build:current-arm64 
unknown shorthand flag: 'v' in -v
See 'docker build --help'.
```

I also have the feeling here that I have overlooked a decisive step

**Comment by runborg** [comment]
@kaplan-michael i think this comes from your PR

**Comment by kaplan-michael** [comment]
@runborg @jkuettner same as the previous issue, it should probably be ` --platform linux/arm64` and looking at it, it should probably be done using `docker buildx` [buildx docs](https://docs.docker.com/engine/reference/commandline/buildx)

TBH, you can omit this step and use the already build image in registry(what make iso-registry uses) 

Also to note, there is some issues with the new build system(it needs some tweeks I have fairly ready, but don't have the time now to submit them(hopefully I'll have a bit of time over the weekend)

**Comment by mowoe** [comment]
Im not really familiar with podman, but i dont see what the `-v` argument should do. `-v` is a `docker run` flag and i dont see a reason why it should be used in a `docker build` command. I would say the whole `-v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static` can be omitted to be honest.

**Comment by kaplan-michael** [comment]
in podman, you can mount it the same for build as for run. with regards to docker, it should be removed everywhere(I thought I did that :facepalm: ) I'll go over it and clean it up when I'm updating the script to use new vyos buildchain.

**Comment by mowoe** [comment]
I see, but why do you need to mount the qemu binary in the container? By specifying `--platform` the commands get executed via qemu anyway if i see it correctly?

**Comment by kaplan-michael** [comment]
on docker yes, on podman it used to be specified with `--arch` flag and then you needed to mount it. once podman added `--platform` it shouldn't be needed either. the arch flag just sets the arch and doesn't do anything else(hence it was mounted)
