### ISSUE TITLE
Not really an issue ;)

### ISSUE THREAD

**Issue by geragcp** [runborg/vyos-pi-builder#2]
Hi there!

I just wanted to say thank you for sharing this repo. It worked flawlessly so far. 
What I was wondering is how to get wireless to work. I suppose the right drivers are missing from the vyos kernel?

Also, I was wondering, on a device such as this one https://www.dfrobot.com/product-2242.html
the second interface requires the r8168-dkms driver. That in turn would require dkms support. Is that even possible? Probably easier to just use the raspbian kernel instead lol. 

I know this isn't a free support forum but I figured I'd ask anyway. Maybe someone else thought about it already. 

Thank you

**Comment by runborg** [comment]
Wireless should be just to get the firmware files in the correct location and it then should work. i was able to get it working a time ago, but i did not save my steps for getting it working. if you get it working please save the steps, as a comment or a PR and it could then be added to the repo as an extra step.

> That in turn would require dkms support. Is that even possible?
no this is not possible, to get dkms running you need a full compile stack and thats not available.
if the driver is available in the linux kernel you should be able to get it compiled in, or if you create a custom kernel you should be able to patch the kernel with the same code as is used to build the dkms module.

**Comment by sedlund** [comment]
you could run vyos in a container on a full linux distro with dkms support

https://github.com/vyos/vyos-build/tree/current/docker-vyos
