### ISSUE TITLE
Raspberry pi 2B support ?

### ISSUE THREAD

**Issue by henri9813** [runborg/vyos-pi-builder#3]
Hello,

Do you support raspberry pi 2B ?

Henri

**Comment by runborg** [comment]
Hi! No, the current vyos ci package build system does only generate 64bit packages, so you are limited to using only 64bit capable cpu’s.. pi3 is the first with this capability.. also both pi3 and pi4 support in this repository is quite experimental, so be prepeared for broken things.. eg, usb3 (the usb ports on the pi) might not work on pi3
