### ISSUE TITLE
build-image.sh fails on "make iso" due to amd64 repo pinning

### ISSUE THREAD

**Issue by jsimpso** [runborg/vyos-pi-builder#5]
Recently when trying to build an image I hit the following error:
```
The following packages have unmet dependencies:
 ntp : Conflicts: time-daemon
 systemd-timesyncd : Conflicts: time-daemon
 vyos-1x : Depends: telegraf (>= 1.20) but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
make: *** [Makefile:32: iso] Error 1
```

This seems to be caused by the `additional_repos` values pulled in by `vyos-build/data/defaults.json` pinning to `amd64` architecture.

I've put together a working fork which applies a workaround of including a custom `VYOS_BUILD_FLAVOR` JSON file which copies the `additional_repos` values from `defaults.json` without the arch pinning: https://github.com/jsimpso/vyos-pi-builder/commit/920734fc8f9f7bd3a099ac3f398249d34285ec5a

I'm happy to raise a PR, but not sure if that's the way you want to approach the problem or whether it's better dealt with upstream in `vyos-build` (I'm not sure how much official support there is for arm64 builds beyond that default flavor config being there).

Thanks!

**Comment by runborg** [comment]
This issue is fixed by upstream pr: https://github.com/vyos/vyos-build/pull/217
